// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvAu1WI2wmAsUbGOjjNdCiLjFNWqjP-rA',
    appId: '1:936591348055:web:9ce474f9eae4cdd9b82e12',
    messagingSenderId: '936591348055',
    projectId: 'smart-wardrobe-9f738',
    authDomain: 'smart-wardrobe-9f738.firebaseapp.com',
    databaseURL: 'https://smart-wardrobe-9f738-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-wardrobe-9f738.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMmSPNGQQmmhOfkWkLhLO3oSJiYBoKY7U',
    appId: '1:936591348055:android:d813824db2901233b82e12',
    messagingSenderId: '936591348055',
    projectId: 'smart-wardrobe-9f738',
    databaseURL: 'https://smart-wardrobe-9f738-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-wardrobe-9f738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdHSJgkDeE13ttO5j7ypZeN2bwRJE7R-8',
    appId: '1:936591348055:ios:249a60bf5e2b9246b82e12',
    messagingSenderId: '936591348055',
    projectId: 'smart-wardrobe-9f738',
    databaseURL: 'https://smart-wardrobe-9f738-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-wardrobe-9f738.appspot.com',
    iosClientId: '936591348055-5mvq959oqvsk38nmh6jt9qf1qk8qrs2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdHSJgkDeE13ttO5j7ypZeN2bwRJE7R-8',
    appId: '1:936591348055:ios:249a60bf5e2b9246b82e12',
    messagingSenderId: '936591348055',
    projectId: 'smart-wardrobe-9f738',
    databaseURL: 'https://smart-wardrobe-9f738-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-wardrobe-9f738.appspot.com',
    iosClientId: '936591348055-5mvq959oqvsk38nmh6jt9qf1qk8qrs2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
